version: '3.8'

services:
  # Laravel/PHP-FPM Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_NAME: Laravel
      APP_KEY: base64:o0Isu6FRxo6U+7P1g6JUFz063DN+BCPRvgO8sbOyews=
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: A_DB_PROGETTO_FIN
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}

      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120

      MEMCACHED_HOST: 127.0.0.1

      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

      MAIL_MAILER: smtp
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: e78f2736aa8bbc
      MAIL_PASSWORD: 0e40edfb260fd6
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "tommasogalistu92@gmail.com"
      MAIL_FROM_NAME: "${APP_NAME}"

      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: ""
      AWS_USE_PATH_STYLE_ENDPOINT: "false"

      PUSHER_APP_ID: ""
      PUSHER_APP_KEY: ""
      PUSHER_APP_SECRET: ""
      PUSHER_HOST: ""
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: mt1

      VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
      VITE_PUSHER_HOST: "${PUSHER_HOST}"
      VITE_PUSHER_PORT: "${PUSHER_PORT}"
      VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
      VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

      FAKE_IP: 203.0.113.1

    networks:
      - app-network

  # Nginx Container
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # MySQL Database Container
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: A_DB_PROGETTO_FIN
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

# Define a shared network
networks:
  app-network:
    driver: bridge

# Persist database data
volumes:
  db_data:
